/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PurchaseOrdersObjectPageObjectPage journey");

        opaTest("Navigate to PurchaseOrdersObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onThePurchaseOrdersList.onFilterBar().iExecuteSearch();

            Then.onThePurchaseOrdersList.onTable().iCheckRows();
            When.onThePurchaseOrdersList.onTable().iPressRow(0);

            Then.onThePurchaseOrdersObjectPage.iSeeThisPage();
        });


        opaTest("Check header facets of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseOrdersObjectPage.onHeader().iCheckHeaderFacet({ facetId: "FieldGroup::KPIs" });
            Then.onThePurchaseOrdersObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::KPIs",
                field: "totalAmount",
                targetAnnotation: ""
            });
            Then.onThePurchaseOrdersObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::KPIs",
                field: "status",
                targetAnnotation: ""
            });
            Then.onThePurchaseOrdersObjectPage.onHeader().iCheckFieldInFieldGroup({
                fieldGroup: "FieldGroup::KPIs",
                field: "priority",
                targetAnnotation: ""
            });
        });

        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onThePurchaseOrdersObjectPage.iCheckNumberOfSections(2);
            When.onThePurchaseOrdersObjectPage.iPressSectionIconTabFilterButton("General");
            Then.onThePurchaseOrdersObjectPage.iCheckSection({ section: "General" });
            Then.onThePurchaseOrdersObjectPage.onForm({ section: "General" }).iCheckField({ property: "poNumber" });
            Then.onThePurchaseOrdersObjectPage.onForm({ section: "General" }).iCheckField({ property: "supplier_ID" });
            Then.onThePurchaseOrdersObjectPage.onForm({ section: "General" }).iCheckField({ property: "priority" });
            Then.onThePurchaseOrdersObjectPage.onForm({ section: "General" }).iCheckField({ property: "status" });
            Then.onThePurchaseOrdersObjectPage.onForm({ section: "General" }).iCheckField({ property: "expectedDate" });
            Then.onThePurchaseOrdersObjectPage.onForm({ section: "General" }).iCheckField({ property: "notes" });
            When.onThePurchaseOrdersObjectPage.iPressSectionIconTabFilterButton("Items");
            Then.onThePurchaseOrdersObjectPage.iCheckSection({ section: "Items" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});